name: "Imma Post"
description: "post blog posts across different platforms"
inputs:
  posts-src: # id of input
    description: "path to the posts folder (defaults to ./blog)"
    required: true
    default: "./blog"
outputs:
  posts-list:
    description: "List of newly created posts"
    value: ${{ steps.get-changes.outputs.posts-list }}
runs:
  using: "composite"
  steps:
    - name: checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: get changed files
      id: get-changes
      run: |
        echo "::set-output name=posts-list::$(git diff --name-only --diff-filter=ACRT ${{ github.event.before == '0000000000000000000000000000000000000000' && '4b825dc642cb6eb9a060e54bf8d69288fbee4904' || github.event.before }}..${{ github.event.after }} | xargs)"
        echo "$(git diff --name-only --diff-filter=ACRT ${{ github.event.before == '0000000000000000000000000000000000000000' && '4b825dc642cb6eb9a060e54bf8d69288fbee4904' || github.event.before }}..${{ github.event.after }} | xargs)"
      shell: bash
    - uses: ./js-action
      with:
        posts-list: ${{ steps.get-changes.outputs.posts-list }}
        repo-path: ${{ github.action_path }}
