on:
  push:
    branches:
      - main

jobs:
  corss_posting_job:
    runs-on: ubuntu-latest
    name: A job cross post blog posts
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: cross posting step
        id: hello
        uses: HarshaVardhanNakkina/github-actions-tut@v2.8
        with:
          posts-src: "./blog"
