on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: HarshaVardhanNakkina/github-actions-tut@v1.8
        with:
          who-to-greet: "Harsha"
      - name: Get the output item
        run: echo "The time was ${{ steps.hello.outputs.random-number }}"
        shell: bash
